"""empty message

Revision ID: 41417aed1ff0
Revises: 
Create Date: 2020-06-14 18:10:18.865490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41417aed1ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('keyword_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    op.drop_table('keyword')
    op.drop_table('article')
    # ### end Alembic commands ###
