"""empty message

Revision ID: 4d0d7e21ee0f
Revises: 9e59ee23466c
Create Date: 2020-06-14 22:32:49.671568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0d7e21ee0f'
down_revision = '9e59ee23466c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('parse_date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'parse_date')
    # ### end Alembic commands ###
