"""empty message

Revision ID: 78f06413e634
Revises: c06b522e6f62
Create Date: 2020-08-20 19:30:42.142551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f06413e634'
down_revision = 'c06b522e6f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('parsed', sa.Boolean(), nullable=True))
    op.add_column('article', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('article', sa.Column('upload_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('file', sa.Column('digital_object_id', sa.String(length=255), nullable=True))
    op.add_column('file', sa.Column('download_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'file', ['download_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'download_url')
    op.drop_column('file', 'digital_object_id')
    op.drop_column('article', 'upload_date')
    op.drop_column('article', 'published')
    op.drop_column('article', 'parsed')
    op.drop_table('author')
    # ### end Alembic commands ###
