"""empty message

Revision ID: 9e59ee23466c
Revises: 8ea1a28d873d
Create Date: 2020-06-14 20:41:47.201747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e59ee23466c'
down_revision = '8ea1a28d873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('parent_request_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'parent_request_url')
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
